# Generated by Django 3.2.5 on 2021-07-04 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter1', models.CharField(max_length=20)),
                ('parameter2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=120)),
                ('answer1', models.CharField(max_length=120)),
                ('answer2', models.CharField(max_length=120)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.parameters')),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('exam_questions', models.ManyToManyField(to='Quiz.questions')),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_answer', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_answer', models.CharField(max_length=120)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.exam')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
